### ISSUE TITLE
lecture_3.tex compile

### ISSUE THREAD

**Issue by jhofman** [jhofman/msd2019-notes#10]
@redouane-dziri: i'm getting the following on a `pdflatex lecture_3.tex`, but seems you were able to compile. any idea what's up?

```
  ! LaTeX Error: There's no line here to end.
  
  See the LaTeX manual or LaTeX Companion for explanation.
  Type  H <return>  for immediate help.
   ...                                              
                                                  
  l.7 \\ I
          n this guest lecture
```

**Comment by redouane-dziri** [comment]
Yes, I should mention it to the student. I believe this happens because they used "//" after section declarations and Latex doesn't like that as it automatically goes to the next line there. It raised warnings but did not prevent compilation on my machine

**Comment by redouane-dziri** [comment]
asked the student to review the file and re-submit a pull request and i'll recompile everything in case something went wrong without my noticing when compiling the file with warnings
